---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: install rabbitmq-server package
  apt: pkg=rabbitmq-server

- name: remove guest user
  rabbitmq_user: name=guest state=absent
