- name: create docker group
  group: name=docker system=yes

- name: create user
  user: >
    name={{ vx_user }} comment="Vexor Worker" groups=docker
    createhome=false system=true home={{ vx_home }}/worker

- name: create working directories
  file: dest={{ item }} state=directory owner={{ vx_user }}
  with_items:
    - "{{ vx_home }}/worker"
    - "{{ vx_home }}/worker/releases"

- name: clone repo
  sudo_user: "{{ vx_user }}"
  git: >
    repo="https://github.com/vexor/vx-worker.git"
    dest={{ vx_home }}/worker/scm version={{ vx_version }}
    update=true force=true bare=true
  register: clone_result

- name: create files
  template: >
    dest={{ item.dest }} src={{ item.src }}
    owner={{ vx_user }} mode={{ item.mode }}
  with_items:
    - { dest: "{{ vx_home}}/bin/worker", src: "worker.j2", mode: "0755" }
    - { dest: "{{ vx_etc_path}}/ci", src: "env.j2", mode: "0640" }
    - { dest: "/etc/init/{{ vx_service }}.conf", src: "upstart.j2", mode: "0755" }
    - { dest: "{{ vx_home }}/worker/deploy.rb", src: "deploy.rb", mode: "0644" }
  register: create_result
  notify: restart service

- name: is deploy exists
  shell: >
    test -f {{ vx_home }}/worker/current/{{ clone_result.after }} && echo "yes" || echo "no"
  register: is_deploy_exists_result
  changed_when: "'no' in is_deploy_exists_result.stdout"

- name: run deploy
  shell: >
    {{ vx_home }}/bin/deploy {{ clone_result.after }} chdir={{ vx_home }}/worker
  sudo_user: "{{ vx_user }}"
  when: is_deploy_exists_result | changed or create_result | changed

