language: c

env:
  - "DIST=precise"
  - "DIST=saucy"

before_script:
  - "sudo service postgresql stop"
  - "env -i HOME=/tmp DIST=$DIST PATH=$PATH DEBIAN_FRONTEND=noninteractive scripts/bootstrap.sh"

script: "sudo env -i HOME=/tmp ANSIBLE_FORCE_COLOR=2 PATH=$PATH DEBIAN_FRONTEND=noninteractive ./play testing -v --skip-tags=docker -c chroot"
