---
- hosts: vexor-mq
  roles:
    - vexor/mq

- hosts: vexor-web
  roles:
    - vexor/web

- hosts: vexor-worker
  roles:
    - vexor/worker

- hosts: vexor-logger
  roles:
    - elasticsearch/install
    - logstash/install
