- name: update apt cache
  apt: update_cache=yes

- name: install request packages
  apt: pkg={{ item }}
  with_items:
    - openjdk-7-jre
    - curl

- name: download and unpack archive
  shell: >
    curl -s {{ elasticsearch_download_url }} | tar -zxf -
    chdir=/opt
    creates=/opt/elasticsearch-{{ elasticsearch_version }}/bin/elasticsearch

- name: create system user
  user: >
    name=elasticsearch comment="elasticsearch daemon"
    createhome=false system=true home=/opt/elasticsearch-{{ elasticsearch_version }}

- name: create directories
  file: dest={{ item }} state=directory owner=elasticsearch
  with_items:
    - /opt/elasticsearch-{{ elasticsearch_version }}/logs
    - /opt/elasticsearch-{{ elasticsearch_version }}/data

- name: setup bind_host
  lineinfile: >
    dest=/opt/elasticsearch-{{ elasticsearch_version }}/config/elasticsearch.yml
    regexp='network.host:'
    line="network.host: {{ elasticsearch_network_host }}"
    state=present
  notify: restart elasticsearch service

- name: setup multicast discovery
  lineinfile: >
    dest=/opt/elasticsearch-{{ elasticsearch_version }}/config/elasticsearch.yml
    regexp='discovery.zen.ping.multicast.enabled:'
    line="discovery.zen.ping.multicast.enabled: {{ elasticsearch_multicast_discovery_enabled }}"
    state=present
  notify: restart elasticsearch service

- name: create service
  template: >
    dest=/etc/init/elasticsearch.conf src=upstart.j2

- name: ensure service up and running
  service: name=elasticsearch enabled=yes state=started
