- name: fix locales
  shell: >
    locale-gen en_US.UTF-8 && dpkg-reconfigure -fnoninteractive locales && update-locale LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US" && touch ~/.locale_ok creates=~/.locale_ok
  when: ansible_distribution == 'Ubuntu'

- name: install packages required for ansible
  apt: pkg={{ item }}
  with_items:
    - "python-apt"
    - "python-pycurl"
    - "python-passlib"

- name: add vexor apt repo key
  apt_key: keyserver=keyserver.ubuntu.com id=0D7276CA

- name: add vexor apt repo
  apt_repository: >
    repo="deb https://s3-eu-west-1.amazonaws.com/bebanjo-apt-ruby/vexor stable main"
    state=present

