- name: restart vxworker service
  service: name={{ vx_worker_user }} state=restarted
  ignore_errors: yes

- name: restart logstash-forwarder service
  service: name=logstash-forwarder state=restarted
