- name: create docker group
  group: name=docker system=yes

- name: create user
  user: >
    name={{ vx_user }} comment="Vexor Worker" groups=docker
    createhome=false system=true home={{ vx_home }}/worker

# Use swapon -s to get the current swap file when we switch on the server
# http://docs.ansible.com/mount_module.html
# https://github.com/ansible/ansible/issues/5241#issuecomment-31438159
# https://github.com/ansible/ansible/pull/6026

# I'm not sure about the parameters and about the src and name options
#- name: create swap
#  mount: name=/dev/sda3 src=/dev/sda3 fstype=swap opts="size=4096m noatime nodiratime" state=mount

- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count=2048
  when: ansible_swaptotal_mb < 2500

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 2500

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present

- name: Turn swap on
  command: swapon -a

- name: set swapiness
  sysctl: name=vm.swappiness value=5 state=present

- name: create working directories
  file: dest={{ item }} state=directory owner={{ vx_user }}
  with_items:
    - "{{ vx_home }}/worker"
    - "{{ vx_home }}/worker/releases"

- name: clone repo
  sudo_user: "{{ vx_user }}"
  git: >
    repo="https://github.com/{{ vx_worker_repo }}.git"
    dest={{ vx_home }}/worker/scm version={{ vx_worker_branch }}
    update=true force=true bare=true
  register: clone_result
  environment:
    GIT_SSL_NO_VERIFY: true
  tags: deploy

- name: create files
  template: >
    dest={{ item.dest }} src={{ item.src }}
    owner={{ vx_user }} mode={{ item.mode }}
  with_items:
    - { dest: "{{ vx_home}}/bin/worker", src: "worker.j2", mode: "0755" }
    - { dest: "{{ vx_etc_path}}/Envfile", src: "env.j2", mode: "0600" }
    - { dest: "/etc/init/{{ vx_service }}.conf", src: "upstart.j2", mode: "0755" }
    - { dest: "{{ vx_home }}/worker/deploy.rb", src: "deploy.rb", mode: "0644" }
  register: create_result
  tags: deploy

- name: is deploy exists
  shell: >
    test -f {{ vx_home }}/worker/current/{{ clone_result.after }} && echo "yes" || echo "no"
  register: is_deploy_exists_result
  changed_when: "'no' in is_deploy_exists_result.stdout"
  tags: deploy

- name: run deploy
  shell: >
    {{ vx_home }}/bin/deploy {{ clone_result.after }} chdir={{ vx_home }}/worker
  sudo_user: "{{ vx_user }}"
  when: is_deploy_exists_result | changed or create_result | changed
  notify: restart vxworker service
  tags: deploy

- name: add logrotate script
  template: src=logrotate.j2 dest=/etc/logrotate.d/{{ vx_user }} mode="0644" owner=root

- include: forwarder.yml
  tags: forwarder
  when: "{{ logstash_server | length > 0 }}"
