- name: install cron job to cleanup old containers
  cron: >
    minute=0
    hour=3,5,7,9,11,13,15,17,19,21,23
    name="cleanup stopped containers"
    cron_file=docker_containers
    user="{{ vx_worker_user }}"
    job="docker rm `docker ps -notrunc -a -q`"
