vexor_worker:

  user:
    name: "vx-worker"
    comment: "vexor worker daemon"
    groups: "docker"
    createhome: false
    system: true
    home: "{{ vexor_worker_home }}"

  repo:
    repo: "https://github.com/vexor/vx-worker.git"
    force: true
    dest: "{{ vexor_worker_home }}"
    version: "{{ vexor_worker_version }}"
    update: true
