---

- name: ensure ubuntu user exits
  user: name=ubuntu comment="Cloud support" shell=/bin/bash state=present

- name: ensure admin group
  group: name=admin state=present

- name: create users
  user: name={{ item.name }} comment="BeBanjo User" shell=/bin/bash password={{ item.password }} state=present
  with_items: ssh_users

- name: setup up authorized_keys
  authorized_key: user={{ item.name }} state=present key="{{ lookup('file', public_keys_dir + item.name + '.pub') }}"
  with_items: ssh_users

- name: add users to group admin
  user: name={{ item.name }} groups=admin append=yes
  with_items: ssh_users
  when: "item.admin == True"

