- name: create user
  user: >
    name={{ vx_web_user }} comment="Vexor Web Worker"
    createhome=false system=true home={{ vx_home }}/web

- name: install required packages
  apt: pkg={{ item }}
  with_items:
    - "nodejs"
    - "libpq-dev"
    - "logrotate"
    - "golang"

- include: web.yml
  tags: vxweb

- include: forwarder.yml
  tags: forwarder
  when: "{{ logstash_server | length > 0 }}"

- include: sockd.yml
  tags: vxsockd
