- name: create user
  user: >
    name={{ vx_user }} comment="Vexor Web Worker"
    createhome=false system=true home={{ vx_home }}/web

- name: create postgresql database
  tags: create_pg_database
  sudo_user: postgres
  postgresql_db: >
    name={{ vx_db_name }}
    encoding='UTF-8'
    login_host=/var/run/postgresql
  register: create_db_result

- name: create hstore extension in postgresql
  sudo_user: postgres
  shell: psql {{ vx_db_name }} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
  when: create_db_result | changed

- name: create postgresql user
  sudo_user: postgres
  postgresql_user: >
    db={{ vx_db_name }}
    name={{ vx_user }}
    password={{ vx_db_password }}
    priv=ALL
    login_host=/var/run/postgresql

- name: create nginx vhost
  template: src=nginx.j2 dest=/etc/nginx/conf.d/{{ vx_user }}.conf
  notify: restart nginx service

- name: remove default nginx site
  file: dest=/etc/nginx/conf.d/default.conf state=absent
  notify: restart nginx service

- name: install required packages
  apt: pkg={{ item }}
  with_items:
    - "nodejs"
    - "libpq-dev"
    - "logrotate"

- name: create working directories
  file: dest={{ item }} state=directory owner={{ vx_user }}
  with_items:
    - "{{ vx_home }}/web"
    - "{{ vx_home }}/web/releases"
    - "{{ vx_home }}/web/shared"
    - "{{ vx_home }}/web/shared/log"
    - "{{ vx_home }}/web/shared/tmp"
    - "{{ vx_home }}/web/shared/tmp/pids"
    - "{{ vx_home }}/web/shared/config"
    - "{{ vx_home }}/web/shared/private"
  tags: deploy

- name: create files
  template: >
    dest={{ item.dest }} src={{ item.src }}
    owner={{ vx_user }} mode={{ item.mode }}
  with_items:
    - { dest: "{{ vx_etc_path}}/Envfile", src: "env.j2", mode: "0600" }
    - { dest: "{{ vx_home }}/web/deploy.rb", src: "deploy.j2", mode: "0644" }
    - { dest: "{{ vx_home }}/web/shared/config/puma.rb", src: "puma.j2", mode: "0644" }
    - { dest: "{{ vx_home }}/bin/{{ vx_user }}-http", src: "vxweb-http.j2", mode: "0755" }
    - { dest: "{{ vx_home }}/bin/{{ vx_user }}-consumer", src: "vxweb-consumer.j2", mode: "0755" }
  register: create_result
  tags: deploy

- name: clone repo
  git: >
    repo="https://github.com/vexor/vx-web.git"
    dest={{ vx_home }}/web/scm version={{ vx_web_version }}
    update=true force=true bare=true
  register: clone_result
  sudo_user: "{{ vx_user }}"
  environment:
    GIT_SSL_NO_VERIFY: true
  tags: deploy

- name: is deploy exists
  shell: >
    test -f {{ vx_home }}/web/current/{{ clone_result.after }} && echo "yes" || echo "no"
  register: is_deploy_exists_result
  changed_when: "'no' in is_deploy_exists_result.stdout"
  tags: deploy

- name: run deploy
  shell: >
    {{ vx_home }}/bin/deploy {{ clone_result.after }} chdir={{ vx_home }}/web
  sudo_user: "{{ vx_user }}"
  when: is_deploy_exists_result | changed or create_result | changed
  tags: deploy
  notify: restart vxweb services

- name: create upstart jobs
  template: dest=/etc/init/{{ vx_user }}-{{ item }}.conf src={{ item }}.upstart.j2
  with_items:
    - "http"
    - "consumer"
  tags: deploy
  notify: restart vxweb services

- name: ensure services up and running
  service: name={{vx_user}}-{{ item }} enabled=yes state=started
  with_items:
    - "http"
    - "consumer"

- name: add logrotate script
  template: src=logrotate.j2 dest=/etc/logrotate.d/{{ vx_user }}

- include: forwarder.yml
  tags: forwarder
  when: "{{ logstash_server | length > 0 }}"
