---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: ensure linux-image-extra is installed
  apt: pkg=linux-image-extra-{{ ansible_kernel }}

- name: install docker package
  tags: docker
  apt: pkg=lxc-docker-{{ docker_version }}
