- name: create docker group
  group: name=docker system=yes

- name: create user
  action: user
  args: vexor_worker.user

- name: checkout worker repo
  action: git
  args: vexor_worker.repo
  register: result

- name: run bundler
  shell: >
    env PATH={{ vexor_worker.bundle.path }} {{ vexor_worker.bundle.install }} chdir={{ vexor_worker.repo.dest }}
  when: result|changed

- name: create log dir
  file:  path="{{ vexor_worker.service.log }}" state=directory owner={{ vexor_worker.user.name }}

- name: create /etc/vexor dir
  file: path="/etc/vexor" state=directory owner={{ vexor_worker.user.name }}

- name: create /etx/vexor/ci
  template: dest=/etc/vexor/ci src="env.j2" owner={{ vexor_worker.user.name }}

- name: create /opt/vexor/sv/worker/log dir
  file: path="/opt/vexor/sv/worker/log" state=directory

- name: create runit log service file
  template: dest=/opt/vexor/sv/worker/log/run src="runit_log.j2" mode=0755

- name: create runit service file
  template: dest=/opt/vexor/sv/worker/run src="runit_service.j2" mode=0755
