elasticsearch_version: "0.90.10"
elasticsearch_download_url: "https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.tar.gz"
elasticsearch_network_host: "127.0.0.1"
elasticsearch_multicast_discovery_enabled: "false"
