- name: add vexor apt repo key
  apt_key: >
    url="http://download.opensuse.org/repositories/home:/dmexe:/vexor/xUbuntu_{{ ansible_distribution_version }}/Release.key"

- name: add vexor apt repo
  apt_repository: >
    repo="deb http://download.opensuse.org/repositories/home:/dmexe:/vexor/xUbuntu_{{ ansible_distribution_version }} /"
    state=present


