---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: ensure linux-image-extra is installed
  tags:
    - docker
    - linux-image-extra
  apt: pkg=linux-image-extra-{{ ansible_kernel }}
  when: ansible_distribution_version != '12.04'

- name: install docker package
  tags: docker
  apt: pkg=lxc-docker-{{ docker_version }}
