---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: ensure linux-image-extra is installed
  tags:
    - docker
    - linux-image-extra
  apt: pkg=linux-image-extra-{{ ansible_kernel }}
  when: ansible_distribution_version != '12.04'

- name: install lxc package
  tags: docker
  apt: pkg=lxc

- name: install docker package
  tags: docker
  apt: pkg=lxc-docker-{{ docker_version }}

- name: create /etc/default/docker
  template: src=docker.j2 dest=/etc/default/docker
  notify:
    - restart docker service
