vx_user: "vxas"
vx_db_name: "{{ vx_user }}_production"
vx_db_pool: 50
vx_db_password_file: >
  {{ credentials_dir }}/{{vx_user}}.postgres
vx_db_password: >
  {{ lookup('password', vx_db_password_file + ' length=30 chars=numbers,digits') }}
vx_db_url: >
  postgres://{{ vx_user }}:{{ vx_db_password }}@localhost/{{ vx_db_name }}?pool={{ vx_db_pool }}

vx_as_branch: "master"
vx_as_password_file: "{{ credentials_dir }}/{{ vx_user }}.htpasswd"
vx_as_password: "{{ lookup('password', vx_as_password_file + ' length=30 chars=numbers,digits') }}"

sdk_username: "{{ lookup('env', 'SDK_USERNAME') }}"
sdk_token: "{{ lookup('env', 'SDK_TOKEN') }}"
sdk_region: "{{ lookup('env', 'SDK_REGION') }}"
