- name: create user
  user: >
    name={{ vx_user }} comment="Vexor Web Worker"
    createhome=false system=true home={{ vx_home }}/web

- name: create postgresql database
  sudo: true
  sudo_user: postgres
  postgresql_db: >
    name={{ vx_db_name }}
    encoding='UTF-8'
    login_host=/var/run/postgresql
  register: create_db_result

- name: create hstore extension in postgresql
  sudo_user: postgres
  shell: psql {{ vx_db_name }} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
  when: create_db_result | changed

- name: create postgresql user
  sudo_user: postgres
  postgresql_user: >
    db={{ vx_db_name }}
    name={{ vx_user }}
    password={{ vx_db_password }}
    priv=ALL
    login_host=/var/run/postgresql

- name: install required packages
  apt: pkg={{ item }}
  with_items:
    - "nodejs"
    - "libpq-dev"

- name: create working directories
  file: dest={{ item }} state=directory owner={{ vx_user }}
  with_items:
    - "{{ vx_home }}/web"
    - "{{ vx_home }}/web/releases"

- name: create files
  template: >
    dest={{ item.dest }} src={{ item.src }}
    owner={{ vx_user }} mode={{ item.mode }}
  with_items:
    - { dest: "{{ vx_etc_path}}/ci", src: "env.j2", mode: "0640" }
    - { dest: "{{ vx_home }}/web/deploy.rb", src: "deploy.rb", mode: "0644" }
  register: create_result

- name: clone repo
  git: >
    repo="https://github.com/vexor/vx-web.git"
    dest={{ vx_home }}/web/scm version={{ vx_version }}
    update=true force=true bare=true
  register: clone_result
  sudo_user: "{{ vx_user }}"

- name: is deploy exists
  shell: >
    test -f {{ vx_home }}/web/current/{{ clone_result.after }} && echo "yes" || echo "no"
  register: is_deploy_exists_result
  changed_when: "'no' in is_deploy_exists_result.stdout"

- name: run deploy
  shell: >
    {{ vx_home }}/bin/deploy {{ clone_result.after }} chdir={{ vx_home }}/web
  sudo_user: "{{ vx_user }}"
  when: is_deploy_exists_result | changed or create_result | changed
