Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :rackspace do |rs|
    rs.username          = ENV['SDK_USERNAME']
    rs.api_key           = ENV['SDK_TOKEN']
    rs.flavor            = /2 GB/
    rs.image             = /Ubuntu 14.04/
    rs.rackspace_region  = ENV['SDK_REGION']
    rs.key_name          = ENV['SDK_KEYNAME']
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
    aws.keypair_name = ENV['AWS_KEY_NAME']

    aws.ami = "ami-018c9568" # Ubuntu Server 14.04 LTS (PV) x64
    aws.instance_type = 'c3.large'
    aws.tags = { 'vexor.test' => 'true' }

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['AWS_KEY_PATH']
  end

  %w{ mq web worker }.each_with_index do |name, idx|
    config.vm.define name.to_sym do |s|
      s.vm.hostname = "#{name}.vexor.test"
    end
  end

  script = <<-EOF
  set -e
  set -x
  EOF

  config.vm.provision "shell", inline: script

end

