# http://developer.rackspace.com/blog/move-fast-and-dont-break-things-testing-with-jenkins-ansible-and-docker.html

- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  when: ansible_distribution == 'CentOS'

- name: ensure CentOS app dependencies are installed for docker-registry
  yum: name={{ item }} state=installed
  with_flattened:
    - common_packages
    - centos_packages
  when: ansible_distribution == 'CentOS'

- name: ensure Ubuntu app dependencies are installed for docker-registry
  apt: name={{ item }} state=installed
  with_flattened:
    - common_packages
    - ubuntu_packages
  when: ansible_distribution == 'Ubuntu'

- name: get docker-registry repo
  git: repo=https://github.com/dotcloud/docker-registry.git dest={{ project_root }}/docker-registry/

- name: use sample docker-registry config
  shell: chdir={{ project_root }}/docker-registry/config/ cp config_sample.yml config.yml

- name: Install python packages
  pip: requirements={{ py_requirements }}

- name: Copy docker-registry init script
  template: src=docker-registry.conf.j2 dest=/etc/init/docker-registry.conf
  notify:
    - restart docker-registry

- name: Start docker-registry service
  service: name=docker-registry state=started

- name: Directory for logging
  file: path=/var/log/docker-registry owner=root group=root mode=666 state=directory

- name: vhost for nginx
  template: src=docker-registry-nginx.conf.j2 dest=/etc/nginx/conf.d/docker-registry.conf owner=root group=root mode=644
  notify: restart nginx service
