project_name: docker-registry
project_root: /opt
py_requirements: "{{ project_root }}/docker-registry/requirements.txt"
common_packages:
  - git
  - python-pip
  - gcc
ubuntu_packages:
  - build-essential
  - python-selinux
  - python-dev
  - python-gevent
  - python-setuptools
  - libevent-2.0-5
  - libevent-dev
  - python-openssl
  - liblzma-dev
centos_packages:
  - libevent-devel
  - libselinux-python
  - python-devel
  - libevent
  - pyOpenSSL
