- name: create instance
  hosts: localhost
  gather_facts: false
  sudo: false
  vars:
    region: eu-west-1
    key_name: dima@evrone.ru
    instance_type: c3.xlarge
    ami: ami-480bea3f
    security_group: ssh-only

  tasks:

  - name: create a new worker
    local_action:
      module: ec2
      key_name: "{{ key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      region: "{{ region }}"
      group: "{{ security_group }}"
      wait: true
      volumes:
      - device_name: /dev/sda1
        volume_size: 40
        delete_on_termination: true
    register: ec2

  - debug: var=ec2

  - name: Add all instance public IPs to vexor-worker
    local_action: add_host hostname={{ item.public_ip }} groupname=vexor-worker
    with_items: ec2.instances

  - name: Add all instance public IPs to vexor-worker-ec2
    local_action: add_host hostname={{ item.public_ip }} groupname=vexor-worker-ec2
    with_items: ec2.instances

  - name: wait for instances to listen on port:22
    local_action: wait_for host={{item.public_ip}} port=22
    with_items: ec2.instances

- name: configure instance
  hosts: vexor-worker-ec2
  gather_facts: true
  sudo: true

  pre_tasks:

  - name: apt update cache
    apt: update_cache=yes

  - name: update system
    apt: upgrade=safe

  - name: doing reboot
    shell: reboot

  - name: wait for server stopped
    sudo: False
    local_action: wait_for host={{inventory_hostname}} port=22 state=stopped

  - name: wait for server up
    sudo: False
    local_action: wait_for host={{inventory_hostname}} port=22

  post_tasks:

  - name: pull docker image
    action: shell docker pull {{ item }}
    register: result
    until: result.stdout.find("Download complete") != -1
    retries: 20
    with_items:
      - "dmexe/vexor-precise-full"
      - "dmexe/vexor-precise"

  roles:
    - vexor/worker

#  - name: destroy all instances
#    ec2: state='absent'
#         region={{ region }}
#         instance_ids={{ item }}
#         wait=true
#    with_items: ec2.instance_ids
