- name: create instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: eu-west-1
    key_name: dima@evrone.ru
    instance_type: c3.xlarge
    ami: ami-480bea3f
    security_group: ssh-only

  tasks:

  - name: create a new worker
    ec2: >
        key_name={{ key_name }}
        instance_type={{ instance_type }}
        image={{ ami }}
        region={{ region }}
        group={{ security_group }}
        wait=true
    register: ec2

  - debug: var=ec2

  - name: Add all instance public IPs to vexor-worker
    add_host: hostname={{ item.public_ip }} groupname=vexor-worker
    with_items: ec2.instances

  - name: Add all instance public IPs to vexor-worker-ec2
    add_host: hostname={{ item.public_ip }} groupname=vexor-worker-ec2
    with_items: ec2.instances

  - name: wait for instances to listen on port:22
    wait_for:
      state=started
      host={{ item.public_ip }}
      port=22
    with_items: ec2.instances

- name: configure instance
  hosts: vexor-worker-ec2
  connection: ssh
  remote_user: ubuntu
  sudo: yes
  gather_facts: True

  pre_tasks:

  - name: apt update cache
    apt: update_cache=yes

  - name: update system
    apt: upgrade=safe

  - name: doing reboot
    shell: reboot

  - name: wait for server stopped
    sudo: False
    local_action: wait_for host={{inventory_hostname}} port=22 state=stopped

  - name: wait for setup up
    sudo: False
    local_action: wait_for host={{inventory_hostname}} port=22

  roles:
    - vexor/worker

#  - name: destroy all instances
#    ec2: state='absent'
#         region={{ region }}
#         instance_ids={{ item }}
#         wait=true
#    with_items: ec2.instance_ids
