- name: Setup current instance
  hosts: localhost
  connection: local
  gather_facts: true
  sudo: false

  tasks:

  - name: add current instance to groups
    # NOT hostname=localhost, ansible does not apply group variables
    local_action: add_host hostname={{ansible_default_ipv4.address}} groupname={{ item }}
    with_items:
    - vexor-worker-rackspace
    - vexor-worker

- name: Configure current instance
  hosts: vexor-worker-rackspace
  gather_facts: true
  sudo: true
  connection: local

  roles:
    - vexor/worker
