---
- hosts: all

- hosts: vexor-mq
  roles:
    - vexor/mq

- hosts: vexor-logger
  roles:
    - vexor/common
    - elasticsearch/install
    - logstash/install

- hosts: vexor-web
  roles:
    - vexor/web

- hosts: vexor-as
  roles:
    - vexor/auto_scale

- hosts: vexor-worker
  roles:
    - vexor/worker

- hosts: vexor-worker-rx
  roles:
    - { role: 'vexor/worker', vx_worker_disable_service: "true" }
    - vexor/rx

- hosts: vexor-worker-ec2
  roles:
    - { role: 'vexor/worker', vx_worker_disable_service: "true" }
    - vexor/ec2
