---
- hosts: vexor
  vars:

- hosts: vexor-mq
  roles:
    - vexor/mq

- hosts: vexor-logger
  roles:
    - vexor/common
    - elasticsearch/install
    - logstash/install

- hosts: vexor-web
  roles:
    - vexor/web

- hosts: vexor-worker
  roles:
    - vexor/worker

