vx_web_num_workers: "{{ ansible_processor_cores }}"
vx_web_hostname: null
vx_web_branch: "master"

vx_user: "vxweb"
vx_db_name: "{{ vx_user }}_production"
vx_db_pool: 50
vx_db_password_file: >
  {{ credentials_dir }}/{{vx_user}}.postgres
vx_db_password: >
  {{ lookup('password', vx_db_password_file + ' length=30 chars=numbers,digits') }}
vx_db_url: >
  postgres://{{ vx_user }}:{{ vx_db_password }}@localhost/{{ vx_db_name }}?pool={{ vx_db_pool }}

github_key: null
github_secret: null

airbrake_api_key: null
airbrake_host: null

gitlab_url: null
