logstash_version: "1.3.3"
logstash_download_url: "https://download.elasticsearch.org/logstash/logstash/logstash-{{ logstash_version }}-flatjar.jar"
logstash_root: "/opt/logstash-{{ logstash_version }}"

logstash_kibana_password_file: "~/.ansible/credentials/{{ inventory_hostname }}/kibana.nginx"
logstash_kibana_password: "{{ lookup('password', logstash_kibana_password_file + ' length=30 chars=numbers,digits') }}"

