logstash_version: "1.3.3"
logstash_download_url: "https://download.elasticsearch.org/logstash/logstash/logstash-{{ logstash_version }}-flatjar.jar"
logstash_root: "/opt/logstash-{{ logstash_version }}"

